version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    networks:
      - akt-dev
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - AKT_UNSECURE=${AKT_UNSECURE}

  frontend:
    build: src/main/reactjs
    ports:
      - "4000:4000"
    networks:
      - akt-dev
    working_dir: /app/reactjs
    volumes:
      - ./src/main/reactjs:/app/reactjs
      - /app/reactjs/node_modules

  postgres:
    build: db
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - akt-dev
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  akt-dev: {}

volumes:
  nodemodules: {}