version: "3.8"
services:
  # Note: backend needs dockerized postgres in order to run!
  backend:
    build: .
    ports:
      - "8080:8080"
    networks:
      - akt-dev
    working_dir: /app
    volumes:
      - ./:/app
  frontend:
    build: src/main/reactjs
    ports:
      - "4000:4000"
    networks:
      - akt-dev
    working_dir: /app/reactjs
    volumes:
      - ./src/main/reactjs:/app/reactjs
      - nodemodules:/app/reactjs/node_modules

networks:
  akt-dev: {}

volumes:
  nodemodules: {}