server:
  port: 8080
  compression:
    enabled: true
spring:
  datasource:
    url: ${postgresql.url:jdbc:postgresql://localhost:5432/postgres}
    username: ${postgresql.username:postgres}
    password: ${postgresql.password:postgres}
  jackson:
    default-property-inclusion: non_null
  jpa:
    open-in-view: false
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  data:
    web:
      pageable:
        max-page-size: 10000
  web:
    resources:
      static-locations: classpath:static/
  thymeleaf:
    prefix: classpath:static/
    templateResolverOrder: 1
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/akt/api/actuator"
      exposure:
        include: "health,info"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
  api-docs:
    path: /api/api-docs
logging:
  level:
    fi:
      oph:
        akt: debug
akt:
  email:
    sending-enabled: ${email.sending-enabled:false}
    ryhmasahkoposti-service-url: ${ryhmasahkoposti-service-url:null}
