server:
  port: 8080
  compression:
    enabled: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  data:
    web:
      pageable:
        max-page-size: 10000
  thymeleaf:
    prefix: "classpath:static/"
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/akt/api/actuator"
      exposure:
        include: "health,info"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
springdoc:
  swagger-ui:
    path: /akt/api/swagger-ui.html
  api-docs:
    path: /akt/api/api-docs