export const CLERK_TRANSLATOR_ADD_AUTHORISATION =
  'CLERK_TRANSLATOR/ADD_AUTHORISATION';
export const CLERK_TRANSLATOR_ADD_AUTHORISATION_ERROR =
  'CLERK_TRANSLATOR/ADD_AUTHORISATION_ERROR';
export const CLERK_TRANSLATOR_ADD_AUTHORISATION_SUCCESS =
  'CLERK_TRANSLATOR/ADD_AUTHORISATION_SUCCESS';
