export const CLERK_TRANSLATOR_OVERVIEW_LOAD = 'CLERK_TRANSLATOR_OVERVIEW/LOAD';
export const CLERK_TRANSLATOR_OVERVIEW_FETCH =
  'CLERK_TRANSLATOR_OVERVIEW/FETCH';
export const CLERK_TRANSLATOR_OVERVIEW_FETCH_SUCCESS =
  'CLERK_TRANSLATOR_OVERVIEW/FETCH_SUCCESS';
export const CLERK_TRANSLATOR_OVERVIEW_FETCH_FAIL =
  'CLERK_TRANSLATOR_OVERVIEW/FETCH_FAIL';
export const CLERK_TRANSLATOR_OVERVIEW_LOADING =
  'CLERK_TRANSLATOR_OVERVIEW/LOADING';

// Translator Details
export const CLERK_TRANSLATOR_OVERVIEW_UPDATE_TRANSLATOR_DETAILS =
  'CLERK_TRANSLATOR_OVERVIEW/UPDATE_TRANSLATOR_DETAILS';
export const CLERK_TRANSLATOR_OVERVIEW_UPDATE_TRANSLATOR_DETAILS_SUCCESS =
  'CLERK_TRANSLATOR_OVERVIEW/UPDATE_TRANSLATOR_DETAILS_SUCCESS';
export const CLERK_TRANSLATOR_OVERVIEW_UPDATE_TRANSLATOR_DETAILS_FAIL =
  'CLERK_TRANSLATOR_OVERVIEW/UPDATE_TRANSLATOR_DETAILS_FAIL';
export const CLERK_TRANSLATOR_OVERVIEW_RESET_UPDATE =
  'CLERK_TRANSLATOR_OVERVIEW/RESET_UPDATE';
export const CLERK_TRANSLATOR_OVERVIEW_CANCEL_UPDATE =
  'CLERK_TRANSLATOR_OVERVIEW/CANCEL_UPDATE';
