export const CLERK_TRANSLATOR_LOAD = 'CLERK_TRANSLATOR_LOAD';
export const CLERK_TRANSLATOR_LOADING = 'CLERK_TRANSLATOR_LOADING';
export const CLERK_TRANSLATOR_ERROR = 'CLERK_TRANSLATOR_ERROR';
export const CLERK_TRANSLATOR_RECEIVED = 'CLERK_TRANSLATOR_RECEIVED';

export const CLERK_TRANSLATOR_SELECT = 'CLERK_TRANSLATOR_SELECT';
export const CLERK_TRANSLATOR_SELECT_ALL_FILTERED =
  'CLERK_TRANSLATOR_SELECT_ALL_FILTERED';
export const CLERK_TRANSLATOR_DESELECT = 'CLERK_TRANSLATOR_DESELECT';
export const CLERK_TRANSLATOR_DESELECT_ALL = 'CLERK_TRANSLATOR_DESELECT_ALL';

export const CLERK_TRANSLATOR_ADD_FILTER = 'CLERK_TRANSLATOR_ADD_FILTER';
export const CLERK_TRANSLATOR_RESET_FILTERS = 'CLERK_TRANSLATOR_RESET_FILTERS';
