export const CLERK_ME_LOAD = 'CLERK_ME/LOAD';
export const CLERK_ME_RECEIVED = 'CLERK_ME/RECEIVED';
export const CLERK_ME_ERROR = 'CLERK_ME/ERROR';
export const CLERK_ME_MOCK_LOAD = 'CLERK_ME/MOCK_LOAD';
