export const MEETING_DATE_LOAD = 'MEETING_DATE/LOAD';
export const MEETING_DATE_LOADING = 'MEETING_DATE/LOADING';
export const MEETING_DATE_ERROR = 'MEETING_DATE/ERROR';
export const MEETING_DATE_RECEIVED = 'MEETING_DATE/RECEIVED';

export const MEETING_DATE_ADD_FILTER = 'MEETING_DATE/ADD_FILTER';
