export const MEETING_DATE_LOAD = 'MEETING_DATE/LOAD';
export const MEETING_DATE_LOADING = 'MEETING_DATE/LOADING';
export const MEETING_DATE_ERROR = 'MEETING_DATE/ERROR';
export const MEETING_DATE_RECEIVED = 'MEETING_DATE/RECEIVED';

export const MEETING_DATE_SELECT = 'MEETING_DATE/SELECT';
export const MEETING_DATE_SELECT_ALL_FILTERED =
  'MEETING_DATE/SELECT_ALL_FILTERED';
export const MEETING_DATE_DESELECT = 'MEETING_DATE/DESELECT';
export const MEETING_DATE_DESELECT_ALL = 'MEETING_DATE/DESELECT_ALL';

export const MEETING_DATE_ADD_FILTER = 'MEETING_DATE/ADD_FILTER';
export const MEETING_DATE_RESET_FILTERS = 'MEETING_DATE/RESET_FILTERS';
