export const PUBLIC_TRANSLATOR_LOAD = 'TRANSLATOR_DETAILS/LOAD';
export const PUBLIC_TRANSLATOR_LOADING = 'TRANSLATOR_DETAILS/LOADING';
export const PUBLIC_TRANSLATOR_RECEIVED = 'TRANSLATOR_DETAILS/RECEIVED';
export const PUBLIC_TRANSLATOR_ERROR = 'TRANSLATOR_DETAILS/ERROR';
export const PUBLIC_TRANSLATOR_ADD_SELECTED = 'TRANSLATOR_DETAILS/ADD_SELECTED';
export const PUBLIC_TRANSLATOR_REMOVE_SELECTED =
  'TRANSLATOR_DETAILS/REMOVE_SELECTED';
export const PUBLIC_TRANSLATOR_ADD_FILTERS = 'TRANSLATOR_DETAILS/ADD_FILTER';
export const PUBLIC_TRANSLATOR_EMPTY_FILTERS =
  'TRANSLATOR_DETAILS/EMPTY_FILTERS';
