export const PUBLIC_TRANSLATOR_LOAD = 'PUBLIC_TRANSLATOR_LOAD';
export const PUBLIC_TRANSLATOR_LOADING = 'PUBLIC_TRANSLATOR_LOADING';
export const PUBLIC_TRANSLATOR_RECEIVED = 'PUBLIC_TRANSLATOR_RECEIVED';
export const PUBLIC_TRANSLATOR_ERROR = 'PUBLIC_TRANSLATOR_ERROR';
export const PUBLIC_TRANSLATOR_ADD_SELECTED = 'PUBLIC_TRANSLATOR_ADD_SELECTED';
export const PUBLIC_TRANSLATOR_REMOVE_SELECTED =
  'PUBLIC_TRANSLATOR_REMOVE_SELECTED';
export const PUBLIC_TRANSLATOR_ADD_FILTERS = 'PUBLIC_TRANSLATOR_ADD_FILTER';
export const PUBLIC_TRANSLATOR_EMPTY_FILTERS =
  'PUBLIC_TRANSLATOR_EMPTY_FILTERS';
