export const MEETING_DATE_ADD = 'MEETING_DATE/ADD';
export const MEETING_DATE_ADD_SUCCESS = 'MEETING_DATE/ADD_SUCCESS';
export const MEETING_DATE_ADD_ERROR = 'MEETING_DATE/ADD_ERROR';
export const MEETING_DATE_REMOVE = 'MEETING_DATE/REMOVE';
export const MEETING_DATE_REMOVE_SUCCESS = 'MEETING_DATE/REMOVE_SUCCESS';
export const MEETING_DATE_REMOVE_ERROR = 'MEETING_DATE/REMOVE_ERROR';

export const MEETING_DATE_ADD_ERROR_TOAST_ADD =
  'MEETING_DATE/ADD_ERROR_TOAST_ADD';
export const MEETING_DATE_ADD_ERROR_TOAST_REMOVE =
  'MEETING_DATE/ADD_ERROR_TOAST_REMOVE';

export const MEETING_DATE_REMOVE_ERROR_TOAST_ADD =
  'MEETING_DATE/REMOVE_ERROR_TOAST_ADD';
export const MEETING_DATE_REMOVE_ERROR_TOAST_REMOVE =
  'MEETING_DATE/REMOVE_ERROR_TOAST_REMOVE';

export const MEETING_DATE_REMOVE_CONFIRM = 'MEETING_DATE/REMOVE';
export const MEETING_DATE_REMOVE_CANCEL = 'MEETING_DATE/CANCEL';

export type RemoveMeetingDateActionType = {
  type: typeof MEETING_DATE_REMOVE;
  meetingDateId: number;
};
