export const TRANSLATOR_DETAILS_LOAD = 'TRANSLATOR_DETAILS/LOAD';
export const TRANSLATOR_DETAILS_LOADING = 'TRANSLATOR_DETAILS/LOADING';
export const TRANSLATOR_DETAILS_RECEIVED = 'TRANSLATOR_DETAILS/RECEIVED';
export const TRANSLATOR_DETAILS_ERROR = 'TRANSLATOR_DETAILS/ERROR';
export const TRANSLATOR_DETAILS_ADD_SELECTED = 'TRANSLATOR_DETAILS/ADD_SELCTED';
export const TRANSLATOR_DETAILS_REMOVE_SELECTED =
  'TRANSLATOR_DETAILS/REMOVE_SELCTED';
export const TRANSLATOR_DETAILS_ADD_FILTERS = 'TRANSLATOR_DETAILS/ADD_FILTER';
export const TRANSLATOR_DETAILS_EMPTY_FILTERS =
  'TRANSLATOR_DETAILS/EMPTY_FILTERS';
