export const TRANSLATOR_DETAILS_LOAD = 'TRANSLATOR_DETAILS/LOAD';
export const TRANSLATOR_DETAILS_LOADING = 'TRANSLATOR_DETAILS/LOADING';
export const TRANSLATOR_DETAILS_RECEIVED = 'TRANSLATOR_DETAILS/RECEIVED';
export const TRANSLATOR_DETAILS_ERROR = 'TRANSLATOR_DETAILS/ERROR';
